source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-coffeescript'
gem 'jekyll-sass-converter'
gem 'kramdown'
gem 'liquid'
gem 'pygments.rb'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'